apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariliakarateka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariliakarateka
  template:
    metadata:
      labels:
        app: mariliakarateka
    spec:
      containers:
      - name: mariliakarateka
        image: patriciasousa/mariliakarateka:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mariliakarateka-service
spec:
  type: NodePort
  selector:
    app: mariliakarateka
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
