apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.fullname" . }}-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "charts.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
{{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort | default 31000 }}
{{- end }}

