name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t patriciasousa/mariliakarateka:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push patriciasousa/mariliakarateka:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: ${{ github.workspace }}/kubeconfig
    steps:
      - uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Criar kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > kubeconfig
          chmod 600 kubeconfig

      - name: Verificar contexto do cluster
        run: kubectl config get-contexts

      - name: Verificar pods no cluster
        run: kubectl get pods --all-namespaces

      - name: Test container local
        run: |
          docker run -d -p 8080:80 --name test-container patriciasousa/mariliakarateka:latest
          sleep 5
          curl --fail http://localhost:8080 || (docker logs test-container && exit 1)
          docker stop test-container
          docker rm test-container

      - name: Deploy com Helm upgrade/install
        run: |
          helm upgrade --install mariliakarateka ./charts \
            --set image.repository=patriciasousa/mariliakarateka \
            --set image.tag=latest \
            --set image.pullPolicy=Always

      - name: Verificar recursos após Helm
        run: |
          kubectl get all
          kubectl describe pods
