name: Deploy Kubernetes local

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Verificar kubectl
        run: kubectl version --client

      - name: Verificar contexto Kubernetes
        run: kubectl config current-context

      - name: Ver pods no cluster
        run: kubectl get pods --all-namespaces

      - name: Deploy com Helm
        run: |
          helm upgrade --install mariliakarateka ./charts \
            --set image.repository=patriciasousa/mariliakarateka \
            --set image.tag=latest
