name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t patriciasousa/mariliakarateka:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push patriciasousa/mariliakarateka:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Helm
        uses: azure/setup-helm@v4
      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG_BASE64 }} # Revertido para KUBECONFIG, mas mantendo o valor BASE64 por enquanto
        run: |
          echo "$KUBECONFIG" | base64 -d > kubeconfig # Decodifica o base64
          export KUBECONFIG=$(pwd)/kubeconfig # Define a variável KUBECONFIG
          kubectl get pods # Comando de teste
          helm upgrade --install MariliaKarateka ./charts \
            --set image.repository=patriciasousa/mariliakarateka \
            --set image.tag=latest
        