name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t patriciasousa/mariliakarateka:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push patriciasousa/mariliakarateka:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Helm
        uses: azure/setup-helm@v4
      - name: Deploy to Kubernetes
        env:
          KUBECONFIG_BASE64: ${{ secrets.KUBECONFIG_BASE64 }} 
        run: |
          echo "$KUBECONFIG_BASE64" | base64 -d > kubeconfig 
          export KUBECONFIG=$(pwd)/kubeconfig 
          kubectl get pods 
          helm upgrade --install MariliaKarateka ./charts \
            --set image.repository=patriciasousa/mariliakarateka \
            --set image.tag=latest